import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import pg from 'pg';
import {randomBytes} from 'node:crypto';
import {generateSecret,generateSync} from 'otplib';
import {seal,unseal,digest,token,passwordHash,passwordMatches} from '../lib/security.js';
import {cleanJob} from '../lib/jobs.js';
process.loadEnvFile('.env.production.local');
process.env.DATA_ENCRYPTION_KEY=randomBytes(32).toString('base64');
process.env.FRONTEND_ORIGIN='https://thejhyefactor.github.io';
const adminUrl=new URL(process.env.DATABASE_URL_UNPOOLED||process.env.DATABASE_URL); adminUrl.searchParams.set('sslmode','verify-full');
const admin=new pg.Client({connectionString:adminUrl.toString()}); await admin.connect();
const schema='qa_tracker_'+randomBytes(6).toString('hex');
await admin.query(`CREATE SCHEMA ${schema}`); await admin.query(`SET search_path TO ${schema}`); await admin.query(fs.readFileSync('docs/schema.sql','utf8'));
adminUrl.searchParams.set('options',`-c search_path=${schema}`); process.env.DATABASE_URL=adminUrl.toString();
const {default:handler}=await import('../api/index.js'); const {db}=await import('../lib/db.js');
const server=http.createServer(handler); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const origin=process.env.FRONTEND_ORIGIN;
async function call(path,{method='GET',body,auth,site=origin}={}) {const headers={}; if(site)headers.Origin=site; if(body!==undefined)headers['Content-Type']='application/json'; if(auth)headers.Authorization=`Bearer ${auth}`; const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}); return {status:r.status,headers:r.headers,body:await r.json()};}
const activation=token(); const secret=generateSecret(); const password=token(); const initial={version:1,jobs:[]};
await admin.query("INSERT INTO tracker_owner(id,totp_encrypted,bootstrap_hash,bootstrap_expires) VALUES(1,$1,$2,now()+interval '48 hours')",[seal(secret),digest(activation)]);
await admin.query('INSERT INTO tracker_data(id,version,encrypted) VALUES(1,1,$1)',[seal(initial)]);
let sessionToken,recovery;
after(async()=>{await new Promise(resolve=>server.close(resolve)); await db().end(); await admin.query(`DROP SCHEMA ${schema} CASCADE`); await admin.end();});
test('Encryption authenticates ciphertext and uses a fresh nonce',()=>{const a=seal({private:'fixture'}),b=seal({private:'fixture'}); assert.notEqual(a,b); assert.deepEqual(unseal(a),{private:'fixture'}); const parts=a.split('.'); const body=Buffer.from(parts[2],'base64'); body[0]^=1; parts[2]=body.toString('base64'); assert.throws(()=>unseal(parts.join('.')));});
test('Password hash is salted, slow and does not accept a different password',async()=>{const a=await passwordHash(password); assert.equal(await passwordMatches(password,a),true); assert.equal(await passwordMatches('wrong',a),false); assert.notEqual(a,await passwordHash(password));});
test('Anonymous reads and forged sessions cannot access jobs',async()=>{assert.equal((await call('/api/jobs')).status,401); assert.equal((await call('/api/jobs',{auth:token()})).status,401);});
test('Foreign origins cannot read or mutate data or use activation',async()=>{assert.equal((await call('/api/jobs',{site:'https://evil.example'})).status,403); assert.equal((await call('/api/setup/info',{method:'POST',site:'https://evil.example',body:{activation}})).status,403);});
test('Setup secret requires its random activation capability',async()=>{assert.equal((await call('/api/setup/info',{method:'POST',body:{activation:token()}})).status,403); const r=await call('/api/setup/info',{method:'POST',body:{activation}}); assert.equal(r.status,200); assert.equal(r.body.secret,secret);});
test('Activation requires a strong password and correct authenticator code',async()=>{assert.equal((await call('/api/setup',{method:'POST',body:{activation,username:'owner',password:'short',otp:'000000'}})).status,400); assert.equal((await call('/api/setup',{method:'POST',body:{activation,username:'owner',password,otp:'notacode'}})).status,401);});
test('Successful owner activation revokes setup capability and stores only hashes',async()=>{const r=await call('/api/setup',{method:'POST',body:{activation,username:'owner',password,otp:generateSync({secret})}}); assert.equal(r.status,200); sessionToken=r.body.token; recovery=r.body.recovery; assert.equal(recovery.length,10); assert.equal((await call('/api/setup/info',{method:'POST',body:{activation}})).status,403); const row=(await admin.query('SELECT * FROM tracker_owner')).rows[0]; assert.equal(row.bootstrap_hash,null); assert.notEqual(row.password_hash,password); assert.equal(row.recovery_hashes.includes(recovery[0]),false);});
test('Authenticated read has no-store and only the exact allowed CORS origin',async()=>{const r=await call('/api/jobs',{auth:sessionToken}); assert.equal(r.status,200); assert.deepEqual(r.body,initial); assert.equal(r.headers.get('cache-control'),'no-store'); assert.equal(r.headers.get('access-control-allow-origin'),origin);});
test('OTP replay is rejected, recovery code is consumed once',async()=>{assert.equal((await call('/api/login',{method:'POST',body:{username:'owner',password,otp:generateSync({secret})}})).status,401); const input={username:'owner',password,otp:recovery[0]}; assert.equal((await call('/api/login',{method:'POST',body:input})).status,200); assert.equal((await call('/api/login',{method:'POST',body:input})).status,401);});
test('Writes are durable, encrypted, backed up and reject stale versions',async()=>{const job={title:'Synthetic test role',company:'Synthetic company',stage:'Applied',reviewStatus:'Not specified',advertStatus:'Not specified',date:'2026-10-05',note:'<img src=x onerror=alert(1)>',url:'https://example.com'}; const r=await call('/api/jobs',{method:'POST',auth:sessionToken,body:{version:1,job}}); assert.equal(r.status,200); assert.equal(r.body.jobs.length,1); assert.equal(r.body.version,2); assert.equal((await call('/api/jobs',{method:'POST',auth:sessionToken,body:{version:1,job}})).status,409); const row=(await admin.query('SELECT encrypted FROM tracker_data')).rows[0]; assert.ok(!row.encrypted.includes('Synthetic')); assert.equal(unseal(row.encrypted).jobs.length,1); assert.equal((await admin.query('SELECT count(*) FROM tracker_backups')).rows[0].count,'1'); const id=r.body.jobs[0].id; assert.equal((await call(`/api/jobs/${id}`,{method:'PATCH',auth:sessionToken,body:{version:2,job:{stage:'Interview'}}})).status,200);});
test('Non-web links, malformed dates and invalid stages are rejected',()=>{const base={title:'x',company:'y',stage:'Applied',reviewStatus:'Not specified',advertStatus:'Not specified'}; assert.throws(()=>cleanJob({...base,url:'javascript:alert(1)'})); assert.throws(()=>cleanJob({...base,date:'2026-02-30'})); assert.throws(()=>cleanJob({...base,stage:'bad'}));});
test('Logout revokes the server session',async()=>{assert.equal((await call('/api/logout',{method:'POST',auth:sessionToken,body:{}})).status,200); assert.equal((await call('/api/jobs',{auth:sessionToken})).status,401);});
test('Expired or idle sessions are rejected',async()=>{const a=token(),b=token(); await admin.query("INSERT INTO tracker_sessions(hash,expires_at,last_seen) VALUES($1,now()-interval '1 second',now()),($2,now()+interval '1 hour',now()-interval '31 minutes')",[digest(a),digest(b)]); assert.equal((await call('/api/jobs',{auth:a})).status,401); assert.equal((await call('/api/jobs',{auth:b})).status,401);});
test('Account rate limit works across requests',async()=>{await admin.query("INSERT INTO tracker_rate_limits(key,hits,window_start) VALUES('login-owner',10,now()) ON CONFLICT(key) DO UPDATE SET hits=10,window_start=now()"); const r=await call('/api/login',{method:'POST',body:{username:'owner',password,otp:'000000'}}); assert.equal(r.status,429); assert.equal(r.headers.get('retry-after'),'900');});
